//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CronusQueryWebApplication.CronusQueryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string no_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string no_ {
            get {
                return this.no_Field;
            }
            set {
                if ((object.ReferenceEquals(this.no_Field, value) != true)) {
                    this.no_Field = value;
                    this.RaisePropertyChanged("no_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relative", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Relative : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string relativeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNo_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string relativeCode {
            get {
                return this.relativeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.relativeCodeField, value) != true)) {
                    this.relativeCodeField = value;
                    this.RaisePropertyChanged("relativeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string empNo_ {
            get {
                return this.empNo_Field;
            }
            set {
                if ((object.ReferenceEquals(this.empNo_Field, value) != true)) {
                    this.empNo_Field = value;
                    this.RaisePropertyChanged("empNo_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string empFirstName {
            get {
                return this.empFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empFirstNameField, value) != true)) {
                    this.empFirstNameField = value;
                    this.RaisePropertyChanged("empFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string empLastName {
            get {
                return this.empLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empLastNameField, value) != true)) {
                    this.empLastNameField = value;
                    this.RaisePropertyChanged("empLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeAbsence", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmployeeAbsence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string causeOfAbsenceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNo_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fromDate {
            get {
                return this.fromDateField;
            }
            set {
                if ((object.ReferenceEquals(this.fromDateField, value) != true)) {
                    this.fromDateField = value;
                    this.RaisePropertyChanged("fromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string causeOfAbsenceCode {
            get {
                return this.causeOfAbsenceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.causeOfAbsenceCodeField, value) != true)) {
                    this.causeOfAbsenceCodeField = value;
                    this.RaisePropertyChanged("causeOfAbsenceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string empNo_ {
            get {
                return this.empNo_Field;
            }
            set {
                if ((object.ReferenceEquals(this.empNo_Field, value) != true)) {
                    this.empNo_Field = value;
                    this.RaisePropertyChanged("empNo_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string empFirstName {
            get {
                return this.empFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empFirstNameField, value) != true)) {
                    this.empFirstNameField = value;
                    this.RaisePropertyChanged("empFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string empLastName {
            get {
                return this.empLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empLastNameField, value) != true)) {
                    this.empLastNameField = value;
                    this.RaisePropertyChanged("empLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CronusQueryService.CronusQueryWebServiceSoap")]
    public interface CronusQueryWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetKeysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeys", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetKeysResponse GetKeys(CronusQueryWebApplication.CronusQueryService.GetKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetKeysResponse> GetKeysAsync(CronusQueryWebApplication.CronusQueryService.GetKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndexes", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetIndexesResponse GetIndexes(CronusQueryWebApplication.CronusQueryService.GetIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetIndexesResponse> GetIndexesAsync(CronusQueryWebApplication.CronusQueryService.GetIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConstraints", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetConstraintsResponse GetConstraints(CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetConstraintsResponse> GetConstraintsAsync(CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetTablesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTables", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetTablesResponse GetTables(CronusQueryWebApplication.CronusQueryService.GetTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTables", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetTablesResponse> GetTablesAsync(CronusQueryWebApplication.CronusQueryService.GetTablesRequest request);
        
        // CODEGEN: Generating message contract since element name GetColumnsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumns", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetColumnsResponse GetColumns(CronusQueryWebApplication.CronusQueryService.GetColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetColumnsResponse> GetColumnsAsync(CronusQueryWebApplication.CronusQueryService.GetColumnsRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetEmployeesResponse GetEmployees(CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetEmployeesResponse> GetEmployeesAsync(CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRelatives", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetRelativesResponse GetRelatives(CronusQueryWebApplication.CronusQueryService.GetRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetRelativesResponse> GetRelativesAsync(CronusQueryWebApplication.CronusQueryService.GetRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAbcenseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAbcense", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetAbcenseResponse GetAbcense(CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAbcense", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetAbcenseResponse> GetAbcenseAsync(CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest request);
        
        // CODEGEN: Generating message contract since element name GetMostAbsentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMostAbsent", ReplyAction="*")]
        CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponse GetMostAbsent(CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMostAbsent", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponse> GetMostAbsentAsync(CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeys", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetKeysRequestBody Body;
        
        public GetKeysRequest() {
        }
        
        public GetKeysRequest(CronusQueryWebApplication.CronusQueryService.GetKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKeysRequestBody {
        
        public GetKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetKeysResponseBody Body;
        
        public GetKeysResponse() {
        }
        
        public GetKeysResponse(CronusQueryWebApplication.CronusQueryService.GetKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetKeysResult;
        
        public GetKeysResponseBody() {
        }
        
        public GetKeysResponseBody(CronusQueryWebApplication.CronusQueryService.ArrayOfString GetKeysResult) {
            this.GetKeysResult = GetKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexes", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetIndexesRequestBody Body;
        
        public GetIndexesRequest() {
        }
        
        public GetIndexesRequest(CronusQueryWebApplication.CronusQueryService.GetIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIndexesRequestBody {
        
        public GetIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetIndexesResponseBody Body;
        
        public GetIndexesResponse() {
        }
        
        public GetIndexesResponse(CronusQueryWebApplication.CronusQueryService.GetIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetIndexesResult;
        
        public GetIndexesResponseBody() {
        }
        
        public GetIndexesResponseBody(CronusQueryWebApplication.CronusQueryService.ArrayOfString GetIndexesResult) {
            this.GetIndexesResult = GetIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConstraints", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetConstraintsRequestBody Body;
        
        public GetConstraintsRequest() {
        }
        
        public GetConstraintsRequest(CronusQueryWebApplication.CronusQueryService.GetConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetConstraintsRequestBody {
        
        public GetConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetConstraintsResponseBody Body;
        
        public GetConstraintsResponse() {
        }
        
        public GetConstraintsResponse(CronusQueryWebApplication.CronusQueryService.GetConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetConstraintsResult;
        
        public GetConstraintsResponseBody() {
        }
        
        public GetConstraintsResponseBody(CronusQueryWebApplication.CronusQueryService.ArrayOfString GetConstraintsResult) {
            this.GetConstraintsResult = GetConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTables", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetTablesRequestBody Body;
        
        public GetTablesRequest() {
        }
        
        public GetTablesRequest(CronusQueryWebApplication.CronusQueryService.GetTablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTablesRequestBody {
        
        public GetTablesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTablesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetTablesResponseBody Body;
        
        public GetTablesResponse() {
        }
        
        public GetTablesResponse(CronusQueryWebApplication.CronusQueryService.GetTablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetTablesResult;
        
        public GetTablesResponseBody() {
        }
        
        public GetTablesResponseBody(CronusQueryWebApplication.CronusQueryService.ArrayOfString GetTablesResult) {
            this.GetTablesResult = GetTablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumns", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetColumnsRequestBody Body;
        
        public GetColumnsRequest() {
        }
        
        public GetColumnsRequest(CronusQueryWebApplication.CronusQueryService.GetColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetColumnsRequestBody {
        
        public GetColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetColumnsResponseBody Body;
        
        public GetColumnsResponse() {
        }
        
        public GetColumnsResponse(CronusQueryWebApplication.CronusQueryService.GetColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetColumnsResult;
        
        public GetColumnsResponseBody() {
        }
        
        public GetColumnsResponseBody(CronusQueryWebApplication.CronusQueryService.ArrayOfString GetColumnsResult) {
            this.GetColumnsResult = GetColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(CronusQueryWebApplication.CronusQueryService.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(CronusQueryWebApplication.CronusQueryService.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(CronusQueryWebApplication.CronusQueryService.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelatives", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetRelativesRequestBody Body;
        
        public GetRelativesRequest() {
        }
        
        public GetRelativesRequest(CronusQueryWebApplication.CronusQueryService.GetRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRelativesRequestBody {
        
        public GetRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetRelativesResponseBody Body;
        
        public GetRelativesResponse() {
        }
        
        public GetRelativesResponse(CronusQueryWebApplication.CronusQueryService.GetRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.Relative[] GetRelativesResult;
        
        public GetRelativesResponseBody() {
        }
        
        public GetRelativesResponseBody(CronusQueryWebApplication.CronusQueryService.Relative[] GetRelativesResult) {
            this.GetRelativesResult = GetRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAbcenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAbcense", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetAbcenseRequestBody Body;
        
        public GetAbcenseRequest() {
        }
        
        public GetAbcenseRequest(CronusQueryWebApplication.CronusQueryService.GetAbcenseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAbcenseRequestBody {
        
        public GetAbcenseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAbcenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAbcenseResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetAbcenseResponseBody Body;
        
        public GetAbcenseResponse() {
        }
        
        public GetAbcenseResponse(CronusQueryWebApplication.CronusQueryService.GetAbcenseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAbcenseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.EmployeeAbsence[] GetAbcenseResult;
        
        public GetAbcenseResponseBody() {
        }
        
        public GetAbcenseResponseBody(CronusQueryWebApplication.CronusQueryService.EmployeeAbsence[] GetAbcenseResult) {
            this.GetAbcenseResult = GetAbcenseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMostAbsentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMostAbsent", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequestBody Body;
        
        public GetMostAbsentRequest() {
        }
        
        public GetMostAbsentRequest(CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMostAbsentRequestBody {
        
        public GetMostAbsentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMostAbsentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMostAbsentResponse", Namespace="http://tempuri.org/", Order=0)]
        public CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponseBody Body;
        
        public GetMostAbsentResponse() {
        }
        
        public GetMostAbsentResponse(CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMostAbsentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetMostAbsentResult;
        
        public GetMostAbsentResponseBody() {
        }
        
        public GetMostAbsentResponseBody(CronusQueryWebApplication.CronusQueryService.ArrayOfString GetMostAbsentResult) {
            this.GetMostAbsentResult = GetMostAbsentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusQueryWebServiceSoapChannel : CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusQueryWebServiceSoapClient : System.ServiceModel.ClientBase<CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap>, CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap {
        
        public CronusQueryWebServiceSoapClient() {
        }
        
        public CronusQueryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusQueryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusQueryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusQueryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetKeysResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetKeys(CronusQueryWebApplication.CronusQueryService.GetKeysRequest request) {
            return base.Channel.GetKeys(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetKeys() {
            CronusQueryWebApplication.CronusQueryService.GetKeysRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetKeysRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetKeysRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetKeysResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetKeys(inValue);
            return retVal.Body.GetKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetKeysResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetKeysAsync(CronusQueryWebApplication.CronusQueryService.GetKeysRequest request) {
            return base.Channel.GetKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetKeysResponse> GetKeysAsync() {
            CronusQueryWebApplication.CronusQueryService.GetKeysRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetKeysRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetKeysRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetIndexesResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetIndexes(CronusQueryWebApplication.CronusQueryService.GetIndexesRequest request) {
            return base.Channel.GetIndexes(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetIndexes() {
            CronusQueryWebApplication.CronusQueryService.GetIndexesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetIndexesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetIndexesRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetIndexesResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetIndexes(inValue);
            return retVal.Body.GetIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetIndexesResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetIndexesAsync(CronusQueryWebApplication.CronusQueryService.GetIndexesRequest request) {
            return base.Channel.GetIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetIndexesResponse> GetIndexesAsync() {
            CronusQueryWebApplication.CronusQueryService.GetIndexesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetIndexesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetIndexesRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetConstraintsResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetConstraints(CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest request) {
            return base.Channel.GetConstraints(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetConstraints() {
            CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetConstraintsRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetConstraintsResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetConstraints(inValue);
            return retVal.Body.GetConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetConstraintsResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetConstraintsAsync(CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest request) {
            return base.Channel.GetConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetConstraintsResponse> GetConstraintsAsync() {
            CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetConstraintsRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetConstraintsRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetTablesResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetTables(CronusQueryWebApplication.CronusQueryService.GetTablesRequest request) {
            return base.Channel.GetTables(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetTables() {
            CronusQueryWebApplication.CronusQueryService.GetTablesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetTablesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetTablesRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetTablesResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetTables(inValue);
            return retVal.Body.GetTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetTablesResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetTablesAsync(CronusQueryWebApplication.CronusQueryService.GetTablesRequest request) {
            return base.Channel.GetTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetTablesResponse> GetTablesAsync() {
            CronusQueryWebApplication.CronusQueryService.GetTablesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetTablesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetTablesRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetTablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetColumnsResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetColumns(CronusQueryWebApplication.CronusQueryService.GetColumnsRequest request) {
            return base.Channel.GetColumns(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetColumns() {
            CronusQueryWebApplication.CronusQueryService.GetColumnsRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetColumnsRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetColumnsRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetColumnsResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetColumns(inValue);
            return retVal.Body.GetColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetColumnsResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetColumnsAsync(CronusQueryWebApplication.CronusQueryService.GetColumnsRequest request) {
            return base.Channel.GetColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetColumnsResponse> GetColumnsAsync() {
            CronusQueryWebApplication.CronusQueryService.GetColumnsRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetColumnsRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetColumnsRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetColumnsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetEmployeesResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetEmployees(CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.Employee[] GetEmployees() {
            CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetEmployeesRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetEmployeesResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetEmployeesResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetEmployeesAsync(CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetEmployeesResponse> GetEmployeesAsync() {
            CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetEmployeesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetEmployeesRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetRelativesResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetRelatives(CronusQueryWebApplication.CronusQueryService.GetRelativesRequest request) {
            return base.Channel.GetRelatives(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.Relative[] GetRelatives() {
            CronusQueryWebApplication.CronusQueryService.GetRelativesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetRelativesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetRelativesRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetRelativesResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetRelatives(inValue);
            return retVal.Body.GetRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetRelativesResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetRelativesAsync(CronusQueryWebApplication.CronusQueryService.GetRelativesRequest request) {
            return base.Channel.GetRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetRelativesResponse> GetRelativesAsync() {
            CronusQueryWebApplication.CronusQueryService.GetRelativesRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetRelativesRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetRelativesRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetAbcenseResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetAbcense(CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest request) {
            return base.Channel.GetAbcense(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.EmployeeAbsence[] GetAbcense() {
            CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetAbcenseRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetAbcenseResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetAbcense(inValue);
            return retVal.Body.GetAbcenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetAbcenseResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetAbcenseAsync(CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest request) {
            return base.Channel.GetAbcenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetAbcenseResponse> GetAbcenseAsync() {
            CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetAbcenseRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetAbcenseRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetAbcenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponse CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetMostAbsent(CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest request) {
            return base.Channel.GetMostAbsent(request);
        }
        
        public CronusQueryWebApplication.CronusQueryService.ArrayOfString GetMostAbsent() {
            CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequestBody();
            CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponse retVal = ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetMostAbsent(inValue);
            return retVal.Body.GetMostAbsentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponse> CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap.GetMostAbsentAsync(CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest request) {
            return base.Channel.GetMostAbsentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.CronusQueryService.GetMostAbsentResponse> GetMostAbsentAsync() {
            CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest inValue = new CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequest();
            inValue.Body = new CronusQueryWebApplication.CronusQueryService.GetMostAbsentRequestBody();
            return ((CronusQueryWebApplication.CronusQueryService.CronusQueryWebServiceSoap)(this)).GetMostAbsentAsync(inValue);
        }
    }
}
