//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileReaderWebApplication.FileReaderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SeSkarpt.se/", ConfigurationName="FileReaderService.FileReaderWebServiceSoap")]
    public interface FileReaderWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://SeSkarpt.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarpt.se/Text", ReplyAction="*")]
        FileReaderWebApplication.FileReaderService.TextResponse Text(FileReaderWebApplication.FileReaderService.TextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarpt.se/Text", ReplyAction="*")]
        System.Threading.Tasks.Task<FileReaderWebApplication.FileReaderService.TextResponse> TextAsync(FileReaderWebApplication.FileReaderService.TextRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Text", Namespace="http://SeSkarpt.se/", Order=0)]
        public FileReaderWebApplication.FileReaderService.TextRequestBody Body;
        
        public TextRequest() {
        }
        
        public TextRequest(FileReaderWebApplication.FileReaderService.TextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarpt.se/")]
    public partial class TextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public TextRequestBody() {
        }
        
        public TextRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TextResponse", Namespace="http://SeSkarpt.se/", Order=0)]
        public FileReaderWebApplication.FileReaderService.TextResponseBody Body;
        
        public TextResponse() {
        }
        
        public TextResponse(FileReaderWebApplication.FileReaderService.TextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarpt.se/")]
    public partial class TextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TextResult;
        
        public TextResponseBody() {
        }
        
        public TextResponseBody(string TextResult) {
            this.TextResult = TextResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileReaderWebServiceSoapChannel : FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileReaderWebServiceSoapClient : System.ServiceModel.ClientBase<FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap>, FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap {
        
        public FileReaderWebServiceSoapClient() {
        }
        
        public FileReaderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileReaderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReaderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReaderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileReaderWebApplication.FileReaderService.TextResponse FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap.Text(FileReaderWebApplication.FileReaderService.TextRequest request) {
            return base.Channel.Text(request);
        }
        
        public string Text(string fileName) {
            FileReaderWebApplication.FileReaderService.TextRequest inValue = new FileReaderWebApplication.FileReaderService.TextRequest();
            inValue.Body = new FileReaderWebApplication.FileReaderService.TextRequestBody();
            inValue.Body.fileName = fileName;
            FileReaderWebApplication.FileReaderService.TextResponse retVal = ((FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap)(this)).Text(inValue);
            return retVal.Body.TextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileReaderWebApplication.FileReaderService.TextResponse> FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap.TextAsync(FileReaderWebApplication.FileReaderService.TextRequest request) {
            return base.Channel.TextAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileReaderWebApplication.FileReaderService.TextResponse> TextAsync(string fileName) {
            FileReaderWebApplication.FileReaderService.TextRequest inValue = new FileReaderWebApplication.FileReaderService.TextRequest();
            inValue.Body = new FileReaderWebApplication.FileReaderService.TextRequestBody();
            inValue.Body.fileName = fileName;
            return ((FileReaderWebApplication.FileReaderService.FileReaderWebServiceSoap)(this)).TextAsync(inValue);
        }
    }
}
