//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CronusWebApplication.CronusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://SeSkarptCronus.se/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idNbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idNbr {
            get {
                return this.idNbrField;
            }
            set {
                if ((object.ReferenceEquals(this.idNbrField, value) != true)) {
                    this.idNbrField = value;
                    this.RaisePropertyChanged("idNbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobTitleField, value) != true)) {
                    this.jobTitleField = value;
                    this.RaisePropertyChanged("jobTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SeSkarptCronus.se/", ConfigurationName="CronusService.CronusWebServiceSoap")]
    public interface CronusWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://SeSkarptCronus.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/HelloWorld", ReplyAction="*")]
        CronusWebApplication.CronusService.HelloWorldResponse HelloWorld(CronusWebApplication.CronusService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.HelloWorldResponse> HelloWorldAsync(CronusWebApplication.CronusService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name idNbr from namespace http://SeSkarptCronus.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/AddEmployee", ReplyAction="*")]
        CronusWebApplication.CronusService.AddEmployeeResponse AddEmployee(CronusWebApplication.CronusService.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.AddEmployeeResponse> AddEmployeeAsync(CronusWebApplication.CronusService.AddEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name idNbr from namespace http://SeSkarptCronus.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/DeleteEmployee", ReplyAction="*")]
        CronusWebApplication.CronusService.DeleteEmployeeResponse DeleteEmployee(CronusWebApplication.CronusService.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.DeleteEmployeeResponse> DeleteEmployeeAsync(CronusWebApplication.CronusService.DeleteEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name idNbr from namespace http://SeSkarptCronus.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/UpdateEmployee", ReplyAction="*")]
        CronusWebApplication.CronusService.UpdateEmployeeResponse UpdateEmployee(CronusWebApplication.CronusService.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.UpdateEmployeeResponse> UpdateEmployeeAsync(CronusWebApplication.CronusService.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://SeSkarptCronus.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/GetEmployees", ReplyAction="*")]
        CronusWebApplication.CronusService.GetEmployeesResponse GetEmployees(CronusWebApplication.CronusService.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeSkarptCronus.se/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.GetEmployeesResponse> GetEmployeesAsync(CronusWebApplication.CronusService.GetEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CronusWebApplication.CronusService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CronusWebApplication.CronusService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarptCronus.se/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployee", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.AddEmployeeRequestBody Body;
        
        public AddEmployeeRequest() {
        }
        
        public AddEmployeeRequest(CronusWebApplication.CronusService.AddEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarptCronus.se/")]
    public partial class AddEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idNbr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        public AddEmployeeRequestBody() {
        }
        
        public AddEmployeeRequestBody(string idNbr, string firstName, string lastName, string jobTitle) {
            this.idNbr = idNbr;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeeResponse", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.AddEmployeeResponseBody Body;
        
        public AddEmployeeResponse() {
        }
        
        public AddEmployeeResponse(CronusWebApplication.CronusService.AddEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddEmployeeResponseBody {
        
        public AddEmployeeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest() {
        }
        
        public DeleteEmployeeRequest(CronusWebApplication.CronusService.DeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarptCronus.se/")]
    public partial class DeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idNbr;
        
        public DeleteEmployeeRequestBody() {
        }
        
        public DeleteEmployeeRequestBody(string idNbr) {
            this.idNbr = idNbr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse() {
        }
        
        public DeleteEmployeeResponse(CronusWebApplication.CronusService.DeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteEmployeeResponseBody {
        
        public DeleteEmployeeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(CronusWebApplication.CronusService.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarptCronus.se/")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idNbr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(string idNbr, string firstName, string lastName, string jobTitle) {
            this.idNbr = idNbr;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(CronusWebApplication.CronusService.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateEmployeeResponseBody {
        
        public UpdateEmployeeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(CronusWebApplication.CronusService.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://SeSkarptCronus.se/", Order=0)]
        public CronusWebApplication.CronusService.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(CronusWebApplication.CronusService.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeSkarptCronus.se/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusWebApplication.CronusService.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(CronusWebApplication.CronusService.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusWebServiceSoapChannel : CronusWebApplication.CronusService.CronusWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusWebServiceSoapClient : System.ServiceModel.ClientBase<CronusWebApplication.CronusService.CronusWebServiceSoap>, CronusWebApplication.CronusService.CronusWebServiceSoap {
        
        public CronusWebServiceSoapClient() {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusWebApplication.CronusService.HelloWorldResponse CronusWebApplication.CronusService.CronusWebServiceSoap.HelloWorld(CronusWebApplication.CronusService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CronusWebApplication.CronusService.HelloWorldRequest inValue = new CronusWebApplication.CronusService.HelloWorldRequest();
            inValue.Body = new CronusWebApplication.CronusService.HelloWorldRequestBody();
            CronusWebApplication.CronusService.HelloWorldResponse retVal = ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.HelloWorldResponse> CronusWebApplication.CronusService.CronusWebServiceSoap.HelloWorldAsync(CronusWebApplication.CronusService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusWebApplication.CronusService.HelloWorldResponse> HelloWorldAsync() {
            CronusWebApplication.CronusService.HelloWorldRequest inValue = new CronusWebApplication.CronusService.HelloWorldRequest();
            inValue.Body = new CronusWebApplication.CronusService.HelloWorldRequestBody();
            return ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusWebApplication.CronusService.AddEmployeeResponse CronusWebApplication.CronusService.CronusWebServiceSoap.AddEmployee(CronusWebApplication.CronusService.AddEmployeeRequest request) {
            return base.Channel.AddEmployee(request);
        }
        
        public void AddEmployee(string idNbr, string firstName, string lastName, string jobTitle) {
            CronusWebApplication.CronusService.AddEmployeeRequest inValue = new CronusWebApplication.CronusService.AddEmployeeRequest();
            inValue.Body = new CronusWebApplication.CronusService.AddEmployeeRequestBody();
            inValue.Body.idNbr = idNbr;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            CronusWebApplication.CronusService.AddEmployeeResponse retVal = ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).AddEmployee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.AddEmployeeResponse> CronusWebApplication.CronusService.CronusWebServiceSoap.AddEmployeeAsync(CronusWebApplication.CronusService.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusWebApplication.CronusService.AddEmployeeResponse> AddEmployeeAsync(string idNbr, string firstName, string lastName, string jobTitle) {
            CronusWebApplication.CronusService.AddEmployeeRequest inValue = new CronusWebApplication.CronusService.AddEmployeeRequest();
            inValue.Body = new CronusWebApplication.CronusService.AddEmployeeRequestBody();
            inValue.Body.idNbr = idNbr;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            return ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).AddEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusWebApplication.CronusService.DeleteEmployeeResponse CronusWebApplication.CronusService.CronusWebServiceSoap.DeleteEmployee(CronusWebApplication.CronusService.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public void DeleteEmployee(string idNbr) {
            CronusWebApplication.CronusService.DeleteEmployeeRequest inValue = new CronusWebApplication.CronusService.DeleteEmployeeRequest();
            inValue.Body = new CronusWebApplication.CronusService.DeleteEmployeeRequestBody();
            inValue.Body.idNbr = idNbr;
            CronusWebApplication.CronusService.DeleteEmployeeResponse retVal = ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).DeleteEmployee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.DeleteEmployeeResponse> CronusWebApplication.CronusService.CronusWebServiceSoap.DeleteEmployeeAsync(CronusWebApplication.CronusService.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusWebApplication.CronusService.DeleteEmployeeResponse> DeleteEmployeeAsync(string idNbr) {
            CronusWebApplication.CronusService.DeleteEmployeeRequest inValue = new CronusWebApplication.CronusService.DeleteEmployeeRequest();
            inValue.Body = new CronusWebApplication.CronusService.DeleteEmployeeRequestBody();
            inValue.Body.idNbr = idNbr;
            return ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).DeleteEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusWebApplication.CronusService.UpdateEmployeeResponse CronusWebApplication.CronusService.CronusWebServiceSoap.UpdateEmployee(CronusWebApplication.CronusService.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public void UpdateEmployee(string idNbr, string firstName, string lastName, string jobTitle) {
            CronusWebApplication.CronusService.UpdateEmployeeRequest inValue = new CronusWebApplication.CronusService.UpdateEmployeeRequest();
            inValue.Body = new CronusWebApplication.CronusService.UpdateEmployeeRequestBody();
            inValue.Body.idNbr = idNbr;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            CronusWebApplication.CronusService.UpdateEmployeeResponse retVal = ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).UpdateEmployee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.UpdateEmployeeResponse> CronusWebApplication.CronusService.CronusWebServiceSoap.UpdateEmployeeAsync(CronusWebApplication.CronusService.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusWebApplication.CronusService.UpdateEmployeeResponse> UpdateEmployeeAsync(string idNbr, string firstName, string lastName, string jobTitle) {
            CronusWebApplication.CronusService.UpdateEmployeeRequest inValue = new CronusWebApplication.CronusService.UpdateEmployeeRequest();
            inValue.Body = new CronusWebApplication.CronusService.UpdateEmployeeRequestBody();
            inValue.Body.idNbr = idNbr;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            return ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusWebApplication.CronusService.GetEmployeesResponse CronusWebApplication.CronusService.CronusWebServiceSoap.GetEmployees(CronusWebApplication.CronusService.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public CronusWebApplication.CronusService.Employee[] GetEmployees() {
            CronusWebApplication.CronusService.GetEmployeesRequest inValue = new CronusWebApplication.CronusService.GetEmployeesRequest();
            inValue.Body = new CronusWebApplication.CronusService.GetEmployeesRequestBody();
            CronusWebApplication.CronusService.GetEmployeesResponse retVal = ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusWebApplication.CronusService.GetEmployeesResponse> CronusWebApplication.CronusService.CronusWebServiceSoap.GetEmployeesAsync(CronusWebApplication.CronusService.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusWebApplication.CronusService.GetEmployeesResponse> GetEmployeesAsync() {
            CronusWebApplication.CronusService.GetEmployeesRequest inValue = new CronusWebApplication.CronusService.GetEmployeesRequest();
            inValue.Body = new CronusWebApplication.CronusService.GetEmployeesRequestBody();
            return ((CronusWebApplication.CronusService.CronusWebServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
    }
}
