//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CronusQueryWebApplication.ServiceReferenceCronusQuery {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://SeskarptCronusQuery", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://SeskarptCronusQuery")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string no_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string no_ {
            get {
                return this.no_Field;
            }
            set {
                if ((object.ReferenceEquals(this.no_Field, value) != true)) {
                    this.no_Field = value;
                    this.RaisePropertyChanged("no_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relative", Namespace="http://SeskarptCronusQuery")]
    [System.SerializableAttribute()]
    public partial class Relative : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string relativeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNo_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string relativeCode {
            get {
                return this.relativeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.relativeCodeField, value) != true)) {
                    this.relativeCodeField = value;
                    this.RaisePropertyChanged("relativeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string empNo_ {
            get {
                return this.empNo_Field;
            }
            set {
                if ((object.ReferenceEquals(this.empNo_Field, value) != true)) {
                    this.empNo_Field = value;
                    this.RaisePropertyChanged("empNo_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string empFirstName {
            get {
                return this.empFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empFirstNameField, value) != true)) {
                    this.empFirstNameField = value;
                    this.RaisePropertyChanged("empFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string empLastName {
            get {
                return this.empLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empLastNameField, value) != true)) {
                    this.empLastNameField = value;
                    this.RaisePropertyChanged("empLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeAbsence", Namespace="http://SeskarptCronusQuery")]
    [System.SerializableAttribute()]
    public partial class EmployeeAbsence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string causeOfAbsenceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empNo_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empLastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fromDate {
            get {
                return this.fromDateField;
            }
            set {
                if ((object.ReferenceEquals(this.fromDateField, value) != true)) {
                    this.fromDateField = value;
                    this.RaisePropertyChanged("fromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string causeOfAbsenceCode {
            get {
                return this.causeOfAbsenceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.causeOfAbsenceCodeField, value) != true)) {
                    this.causeOfAbsenceCodeField = value;
                    this.RaisePropertyChanged("causeOfAbsenceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string empNo_ {
            get {
                return this.empNo_Field;
            }
            set {
                if ((object.ReferenceEquals(this.empNo_Field, value) != true)) {
                    this.empNo_Field = value;
                    this.RaisePropertyChanged("empNo_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string empFirstName {
            get {
                return this.empFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empFirstNameField, value) != true)) {
                    this.empFirstNameField = value;
                    this.RaisePropertyChanged("empFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string empLastName {
            get {
                return this.empLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.empLastNameField, value) != true)) {
                    this.empLastNameField = value;
                    this.RaisePropertyChanged("empLastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SeskarptCronusQuery", ConfigurationName="ServiceReferenceCronusQuery.CronusQueryWebServiceSoap")]
    public interface CronusQueryWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetKeysResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetKeys", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponse GetKeys(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponse> GetKeysAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetIndexesResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetIndexes", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponse GetIndexes(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponse> GetIndexesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetConstraintsResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetConstraints", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponse GetConstraints(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponse> GetConstraintsAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetTablesResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetTables", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponse GetTables(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetTables", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponse> GetTablesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest request);
        
        // CODEGEN: Generating message contract since element name GetColumnsResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetColumns", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponse GetColumns(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponse> GetColumnsAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetEmployees", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponse GetEmployees(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponse> GetEmployeesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name GetRelativesResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetRelatives", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponse GetRelatives(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponse> GetRelativesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAbcenseResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetAbcense", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponse GetAbcense(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetAbcense", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponse> GetAbcenseAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest request);
        
        // CODEGEN: Generating message contract since element name GetMostAbsentResult from namespace http://SeskarptCronusQuery is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetMostAbsent", ReplyAction="*")]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponse GetMostAbsent(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SeskarptCronusQuery/GetMostAbsent", ReplyAction="*")]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponse> GetMostAbsentAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeys", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequestBody Body;
        
        public GetKeysRequest() {
        }
        
        public GetKeysRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKeysRequestBody {
        
        public GetKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeysResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponseBody Body;
        
        public GetKeysResponse() {
        }
        
        public GetKeysResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetKeysResult;
        
        public GetKeysResponseBody() {
        }
        
        public GetKeysResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetKeysResult) {
            this.GetKeysResult = GetKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexes", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequestBody Body;
        
        public GetIndexesRequest() {
        }
        
        public GetIndexesRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIndexesRequestBody {
        
        public GetIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexesResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponseBody Body;
        
        public GetIndexesResponse() {
        }
        
        public GetIndexesResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetIndexesResult;
        
        public GetIndexesResponseBody() {
        }
        
        public GetIndexesResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetIndexesResult) {
            this.GetIndexesResult = GetIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConstraints", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequestBody Body;
        
        public GetConstraintsRequest() {
        }
        
        public GetConstraintsRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetConstraintsRequestBody {
        
        public GetConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConstraintsResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponseBody Body;
        
        public GetConstraintsResponse() {
        }
        
        public GetConstraintsResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetConstraintsResult;
        
        public GetConstraintsResponseBody() {
        }
        
        public GetConstraintsResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetConstraintsResult) {
            this.GetConstraintsResult = GetConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTables", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequestBody Body;
        
        public GetTablesRequest() {
        }
        
        public GetTablesRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTablesRequestBody {
        
        public GetTablesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTablesResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponseBody Body;
        
        public GetTablesResponse() {
        }
        
        public GetTablesResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetTablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetTablesResult;
        
        public GetTablesResponseBody() {
        }
        
        public GetTablesResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetTablesResult) {
            this.GetTablesResult = GetTablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumns", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequestBody Body;
        
        public GetColumnsRequest() {
        }
        
        public GetColumnsRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetColumnsRequestBody {
        
        public GetColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnsResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponseBody Body;
        
        public GetColumnsResponse() {
        }
        
        public GetColumnsResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetColumnsResult;
        
        public GetColumnsResponseBody() {
        }
        
        public GetColumnsResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetColumnsResult) {
            this.GetColumnsResult = GetColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelatives", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequestBody Body;
        
        public GetRelativesRequest() {
        }
        
        public GetRelativesRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRelativesRequestBody {
        
        public GetRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelativesResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponseBody Body;
        
        public GetRelativesResponse() {
        }
        
        public GetRelativesResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.Relative[] GetRelativesResult;
        
        public GetRelativesResponseBody() {
        }
        
        public GetRelativesResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.Relative[] GetRelativesResult) {
            this.GetRelativesResult = GetRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAbcenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAbcense", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequestBody Body;
        
        public GetAbcenseRequest() {
        }
        
        public GetAbcenseRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAbcenseRequestBody {
        
        public GetAbcenseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAbcenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAbcenseResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponseBody Body;
        
        public GetAbcenseResponse() {
        }
        
        public GetAbcenseResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetAbcenseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.EmployeeAbsence[] GetAbcenseResult;
        
        public GetAbcenseResponseBody() {
        }
        
        public GetAbcenseResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.EmployeeAbsence[] GetAbcenseResult) {
            this.GetAbcenseResult = GetAbcenseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMostAbsentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMostAbsent", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequestBody Body;
        
        public GetMostAbsentRequest() {
        }
        
        public GetMostAbsentRequest(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMostAbsentRequestBody {
        
        public GetMostAbsentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMostAbsentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMostAbsentResponse", Namespace="http://SeskarptCronusQuery", Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponseBody Body;
        
        public GetMostAbsentResponse() {
        }
        
        public GetMostAbsentResponse(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SeskarptCronusQuery")]
    public partial class GetMostAbsentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetMostAbsentResult;
        
        public GetMostAbsentResponseBody() {
        }
        
        public GetMostAbsentResponseBody(CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetMostAbsentResult) {
            this.GetMostAbsentResult = GetMostAbsentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusQueryWebServiceSoapChannel : CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusQueryWebServiceSoapClient : System.ServiceModel.ClientBase<CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap>, CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap {
        
        public CronusQueryWebServiceSoapClient() {
        }
        
        public CronusQueryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusQueryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusQueryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusQueryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetKeys(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest request) {
            return base.Channel.GetKeys(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetKeys() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetKeys(inValue);
            return retVal.Body.GetKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetKeysAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest request) {
            return base.Channel.GetKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysResponse> GetKeysAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetKeysRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetIndexes(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest request) {
            return base.Channel.GetIndexes(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetIndexes() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetIndexes(inValue);
            return retVal.Body.GetIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetIndexesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest request) {
            return base.Channel.GetIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesResponse> GetIndexesAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetIndexesRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetConstraints(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest request) {
            return base.Channel.GetConstraints(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetConstraints() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetConstraints(inValue);
            return retVal.Body.GetConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetConstraintsAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest request) {
            return base.Channel.GetConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsResponse> GetConstraintsAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetConstraintsRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetTables(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest request) {
            return base.Channel.GetTables(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetTables() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetTables(inValue);
            return retVal.Body.GetTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetTablesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest request) {
            return base.Channel.GetTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesResponse> GetTablesAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetTablesRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetTablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetColumns(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest request) {
            return base.Channel.GetColumns(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetColumns() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetColumns(inValue);
            return retVal.Body.GetColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetColumnsAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest request) {
            return base.Channel.GetColumnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsResponse> GetColumnsAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetColumnsRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetColumnsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetEmployees(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.Employee[] GetEmployees() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetEmployeesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesResponse> GetEmployeesAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetEmployeesRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetRelatives(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest request) {
            return base.Channel.GetRelatives(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.Relative[] GetRelatives() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetRelatives(inValue);
            return retVal.Body.GetRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetRelativesAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest request) {
            return base.Channel.GetRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesResponse> GetRelativesAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetRelativesRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetAbcense(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest request) {
            return base.Channel.GetAbcense(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.EmployeeAbsence[] GetAbcense() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetAbcense(inValue);
            return retVal.Body.GetAbcenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetAbcenseAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest request) {
            return base.Channel.GetAbcenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseResponse> GetAbcenseAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetAbcenseRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetAbcenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponse CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetMostAbsent(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest request) {
            return base.Channel.GetMostAbsent(request);
        }
        
        public CronusQueryWebApplication.ServiceReferenceCronusQuery.ArrayOfString GetMostAbsent() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequestBody();
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponse retVal = ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetMostAbsent(inValue);
            return retVal.Body.GetMostAbsentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponse> CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap.GetMostAbsentAsync(CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest request) {
            return base.Channel.GetMostAbsentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentResponse> GetMostAbsentAsync() {
            CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest inValue = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequest();
            inValue.Body = new CronusQueryWebApplication.ServiceReferenceCronusQuery.GetMostAbsentRequestBody();
            return ((CronusQueryWebApplication.ServiceReferenceCronusQuery.CronusQueryWebServiceSoap)(this)).GetMostAbsentAsync(inValue);
        }
    }
}
