//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBReaderForm.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Seskarpt.se", ConfigurationName="ServiceReference1.WebServiceDBReaderSoap")]
    public interface WebServiceDBReaderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCollection(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCollectionAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetCustomers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBReaderForm.ServiceReference1.Customer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<DBReaderForm.ServiceReference1.Customer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetDestinations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBReaderForm.ServiceReference1.Destination[] GetDestinations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetDestinations", ReplyAction="*")]
        System.Threading.Tasks.Task<DBReaderForm.ServiceReference1.Destination[]> GetDestinationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetBookings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DBReaderForm.ServiceReference1.Booking[] GetBookings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Seskarpt.se/GetBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<DBReaderForm.ServiceReference1.Booking[]> GetBookingsAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Seskarpt.se")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idNbrField;
        
        private string nameField;
        
        private string addressField;
        
        private string ssnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idNbr {
            get {
                return this.idNbrField;
            }
            set {
                this.idNbrField = value;
                this.RaisePropertyChanged("idNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
                this.RaisePropertyChanged("ssn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Seskarpt.se")]
    public partial class Booking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerNbrField;
        
        private string destinationNbrField;
        
        private string dateOutField;
        
        private string dateHomeField;
        
        private string bookingNbrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string customerNbr {
            get {
                return this.customerNbrField;
            }
            set {
                this.customerNbrField = value;
                this.RaisePropertyChanged("customerNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string destinationNbr {
            get {
                return this.destinationNbrField;
            }
            set {
                this.destinationNbrField = value;
                this.RaisePropertyChanged("destinationNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dateOut {
            get {
                return this.dateOutField;
            }
            set {
                this.dateOutField = value;
                this.RaisePropertyChanged("dateOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dateHome {
            get {
                return this.dateHomeField;
            }
            set {
                this.dateHomeField = value;
                this.RaisePropertyChanged("dateHome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bookingNbr {
            get {
                return this.bookingNbrField;
            }
            set {
                this.bookingNbrField = value;
                this.RaisePropertyChanged("bookingNbr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Seskarpt.se")]
    public partial class Destination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string destinationNbrField;
        
        private string cityField;
        
        private string countryField;
        
        private string hotelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string destinationNbr {
            get {
                return this.destinationNbrField;
            }
            set {
                this.destinationNbrField = value;
                this.RaisePropertyChanged("destinationNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
                this.RaisePropertyChanged("hotel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDBReaderSoapChannel : DBReaderForm.ServiceReference1.WebServiceDBReaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDBReaderSoapClient : System.ServiceModel.ClientBase<DBReaderForm.ServiceReference1.WebServiceDBReaderSoap>, DBReaderForm.ServiceReference1.WebServiceDBReaderSoap {
        
        public WebServiceDBReaderSoapClient() {
        }
        
        public WebServiceDBReaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDBReaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDBReaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDBReaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable GetCollection(string query) {
            return base.Channel.GetCollection(query);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCollectionAsync(string query) {
            return base.Channel.GetCollectionAsync(query);
        }
        
        public DBReaderForm.ServiceReference1.Customer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<DBReaderForm.ServiceReference1.Customer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public DBReaderForm.ServiceReference1.Destination[] GetDestinations() {
            return base.Channel.GetDestinations();
        }
        
        public System.Threading.Tasks.Task<DBReaderForm.ServiceReference1.Destination[]> GetDestinationsAsync() {
            return base.Channel.GetDestinationsAsync();
        }
        
        public DBReaderForm.ServiceReference1.Booking[] GetBookings() {
            return base.Channel.GetBookings();
        }
        
        public System.Threading.Tasks.Task<DBReaderForm.ServiceReference1.Booking[]> GetBookingsAsync() {
            return base.Channel.GetBookingsAsync();
        }
    }
}
